#!/usr/bin/env bash

php artisan optimize:clear

#!/bin/bash
apt-get update
apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev
docker-php-ext-configure gd --with-freetype --with-jpeg
docker-php-ext-install gd

chmod +x install-gd.sh


/opt/docker/bin/entrypoint.sh supervisord
